on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          github_token: ${{ secrets.CORNE_TOKEN }}
      - name: Run post-commit script
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          ./copy-and-commit-keymap.sh  # run
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
